# Generated by Django 3.2.4 on 2021-06-11 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoaiTT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TTId', models.CharField(max_length=20, verbose_name='Ký hiệu TT')),
            ],
            options={
                'verbose_name_plural': 'Loại tờ trình',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RoomID', models.CharField(max_length=30, verbose_name='Ký hiệu phòng')),
                ('quantity', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Phòng ban',
            },
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10)),
                ('yearQuantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ToTrinh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TTtitle', models.CharField(max_length=150, verbose_name='Tên tờ trình')),
                ('TTText', models.TextField(blank=True, max_length=500, null=True, verbose_name='Nội dung tóm tắt')),
                ('Created_on', models.DateField(auto_now_add=True, verbose_name='Ngày lấy số')),
                ('idByYear', models.IntegerField(default=0)),
                ('RoomId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='CreNumb.room', verbose_name='Phòng')),
                ('TTId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CreNumb.loaitt', verbose_name='Loại tờ trình')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
            ],
            options={
                'verbose_name_plural': 'Tờ trình',
            },
        ),
    ]
