# Generated by Django 3.2.4 on 2021-06-09 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CreNumb', '0002_rename_creted_on_totrinh_created_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='totrinh',
            name='Count_on_Room',
        ),
        migrations.RemoveField(
            model_name='totrinh',
            name='Count_on_Year',
        ),
        migrations.AlterField(
            model_name='totrinh',
            name='SoTT',
            field=models.CharField(max_length=50, verbose_name='Số tờ trình'),
        ),
        migrations.AlterField(
            model_name='totrinh',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='auth.user', verbose_name='Người tạo'),
        ),
    ]
