# Generated by Django 3.2.4 on 2021-06-09 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CreNumb', '0003_auto_20210609_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totrinh',
            name='user',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
    ]
