# Generated by Django 3.2.4 on 2021-06-09 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CreNumb', '0004_alter_totrinh_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totrinh',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='auth.user', verbose_name='Người tạo'),
        ),
    ]
